-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-03-23 16:21:29 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE actores (
    id_actor  NUMBER(10) NOT NULL,
    nombre    VARCHAR2(20) NOT NULL,
    edad      NUMBER(5) NOT NULL,
    genero    VARCHAR2(10) NOT NULL,
    pais      VARCHAR2(10) NOT NULL,
    estilo    VARCHAR2(10) NOT NULL
);

ALTER TABLE actores ADD CONSTRAINT actores_pk PRIMARY KEY ( id_actor );

CREATE TABLE canciones (
    id_cancion              NUMBER(10) NOT NULL,
    tipo                    VARCHAR2(10) NOT NULL,
    duracion                VARCHAR2(10) NOT NULL,
    letra                   VARCHAR2(400) NOT NULL,
    link_cancion            VARCHAR2(15) NOT NULL,
    genero                  VARCHAR2(10) NOT NULL,
    productor_id_productor  NUMBER(10) NOT NULL,
    musico_id_musico        NUMBER(10) NOT NULL
);

ALTER TABLE canciones ADD CONSTRAINT canciones_pk PRIMARY KEY ( id_cancion );

CREATE TABLE canciones_favoritas (
    id_favorito           NUMBER(10) NOT NULL,
    usuarios_id_usuario   NUMBER(10) NOT NULL,
    canciones_id_cancion  NUMBER(10) NOT NULL
);

ALTER TABLE canciones_favoritas ADD CONSTRAINT canciones_favoritas_pk PRIMARY KEY ( id_favorito );

CREATE TABLE descargas_canciones (
    id_descarga           NUMBER(10) NOT NULL,
    fecha_inicio          DATE NOT NULL,
    estado_actual         VARCHAR2(10) NOT NULL,
    cantidad              NUMBER(5) NOT NULL,
    usuarios_id_usuario   NUMBER(10) NOT NULL,
    canciones_id_cancion  NUMBER(10) NOT NULL
);

ALTER TABLE descargas_canciones ADD CONSTRAINT descargas_canciones_pk PRIMARY KEY ( id_descarga );

CREATE TABLE descargas_pelicula (
    id_descarga            NUMBER(10) NOT NULL,
    fecha_inicio           DATE NOT NULL,
    estado_actual          VARCHAR2(10) NOT NULL,
    cantidad               NUMBER(5) NOT NULL,
    usuarios_id_usuario    NUMBER(10) NOT NULL,
    peliculas_id_pelicula  NUMBER(10) NOT NULL
);

ALTER TABLE descargas_pelicula ADD CONSTRAINT descargas_pelicula_pk PRIMARY KEY ( id_descarga );

CREATE TABLE descargas_series_tv (
    id_descarga            NUMBER(10) NOT NULL,
    fecha_inicio           DATE NOT NULL,
    estado_actual          VARCHAR2(10) NOT NULL,
    cantidad               NUMBER(5) NOT NULL,
    usuarios_id_usuario    NUMBER(10) NOT NULL,
    series_tv_id_serie_tv  NUMBER(10) NOT NULL
);

ALTER TABLE descargas_series_tv ADD CONSTRAINT descargas_series_tv_pk PRIMARY KEY ( id_descarga );

CREATE TABLE directores (
    id_director  NUMBER(10) NOT NULL,
    nombre       VARCHAR2(10) NOT NULL,
    edad         NUMBER(5) NOT NULL,
    genero       VARCHAR2(10) NOT NULL,
    pais         VARCHAR2(10) NOT NULL,
    estilo       VARCHAR2(10) NOT NULL
);

ALTER TABLE directores ADD CONSTRAINT directores_pk PRIMARY KEY ( id_director );

CREATE TABLE formas_pago (
    id                   NUMBER(10) NOT NULL,
    num_tarjeta          VARCHAR2(15) NOT NULL,
    nombre_propetario    VARCHAR2(20) NOT NULL,
    fecha_vencimiento    DATE NOT NULL,
    cvv                  NUMBER(5) NOT NULL,
    tipo                 VARCHAR2(10) NOT NULL,
    usuarios_id_usuario  NUMBER(10) NOT NULL
);

ALTER TABLE formas_pago ADD CONSTRAINT formas_pago_pk PRIMARY KEY ( id );

CREATE TABLE musico (
    id_musico  NUMBER(10) NOT NULL,
    nombre     VARCHAR2(10) NOT NULL,
    genero     VARCHAR2(5) NOT NULL,
    pais       VARCHAR2(10) NOT NULL,
    edad       NUMBER(5) NOT NULL,
    estilo     VARCHAR2(10) NOT NULL
);

ALTER TABLE musico ADD CONSTRAINT musico_pk PRIMARY KEY ( id_musico );

CREATE TABLE participaciones (
    id_participacion    NUMBER(10) NOT NULL,
    actores_id_actor    NUMBER(10) NOT NULL,
    reparto_id_reparto  NUMBER(10)
);

ALTER TABLE participaciones ADD CONSTRAINT participaciones_pk PRIMARY KEY ( id_participacion );

CREATE TABLE peliculas (
    id_pelicula             NUMBER(10) NOT NULL,
    titulo                  VARCHAR2(10) NOT NULL,
    anno                    VARCHAR2(10) NOT NULL,
    pais                    VARCHAR2(10) NOT NULL,
    estudio                 VARCHAR2(10) NOT NULL,
    genero                  VARCHAR2(10) NOT NULL,
    clasificacion           VARCHAR2(10) NOT NULL,
    duracion                VARCHAR2(10) NOT NULL,
    categoria               VARCHAR2(10) NOT NULL,
    directores_id_director  NUMBER(10) NOT NULL,
    reparto_id_reparto      NUMBER(10)
);

ALTER TABLE peliculas ADD CONSTRAINT peliculas_pk PRIMARY KEY ( id_pelicula );

CREATE TABLE peliculas_favoritas (
    id_favorito            NUMBER(10) NOT NULL,
    usuarios_id_usuario    NUMBER(10) NOT NULL,
    peliculas_id_pelicula  NUMBER(10) NOT NULL
);

ALTER TABLE peliculas_favoritas ADD CONSTRAINT peliculas_favoritas_pk PRIMARY KEY ( id_favorito );

CREATE TABLE productor (
    id_productor  NUMBER(10) NOT NULL,
    nombre        VARCHAR2(10) NOT NULL,
    genero        VARCHAR2(10) NOT NULL,
    pais          VARCHAR2(10) NOT NULL,
    edad          NUMBER(5) NOT NULL,
    estilo        VARCHAR2(10) NOT NULL
);

ALTER TABLE productor ADD CONSTRAINT productor_pk PRIMARY KEY ( id_productor );

CREATE TABLE reparto (
    id_reparto NUMBER(10) NOT NULL
);

ALTER TABLE reparto ADD CONSTRAINT reparto_pk PRIMARY KEY ( id_reparto );

CREATE TABLE reproducciones_canciones (
    id_reproduccion       NUMBER(10) NOT NULL,
    fecha_inicio          DATE NOT NULL,
    estado_actual         VARCHAR2(10) NOT NULL,
    cant_reproducciones   NUMBER(5) NOT NULL,
    canciones_id_cancion  NUMBER(10) NOT NULL,
    usuarios_id_usuario   NUMBER(10) NOT NULL
);

ALTER TABLE reproducciones_canciones ADD CONSTRAINT reproducciones_canciones_pk PRIMARY KEY ( id_reproduccion );

CREATE TABLE reproducciones_pelicula (
    id_reproduccion        NUMBER(10) NOT NULL,
    fecha_inicio           DATE NOT NULL,
    estado_actual          VARCHAR2(10) NOT NULL,
    cant_reproducciones    NUMBER(5) NOT NULL,
    peliculas_id_pelicula  NUMBER(10) NOT NULL,
    usuarios_id_usuario    NUMBER(10) NOT NULL
);

ALTER TABLE reproducciones_pelicula ADD CONSTRAINT reproducciones_pelicula_pk PRIMARY KEY ( id_reproduccion );

CREATE TABLE reproducciones_series_tv (
    id_reproduccion        NUMBER(10) NOT NULL,
    fecha_inicio           DATE NOT NULL,
    estado_actual          VARCHAR2(10) NOT NULL,
    cant_reproducciones    NUMBER(5) NOT NULL,
    usuarios_id_usuario    NUMBER(10) NOT NULL,
    series_tv_id_serie_tv  NUMBER(10) NOT NULL
);

ALTER TABLE reproducciones_series_tv ADD CONSTRAINT reproducciones_series_tv_pk PRIMARY KEY ( id_reproduccion );

CREATE TABLE saga_pelicula (
    id_saga                NUMBER(10) NOT NULL,
    titulo                 VARCHAR2(10) NOT NULL,
    anno                   DATE NOT NULL,
    categoria              VARCHAR2(10) NOT NULL,
    genero                 VARCHAR2(10) NOT NULL,
    id_serie_tv            NUMBER(10),
    peliculas_id_pelicula  NUMBER(10) NOT NULL
);

ALTER TABLE saga_pelicula ADD CONSTRAINT saga_pelicula_pk PRIMARY KEY ( id_saga );

CREATE TABLE saga_serie_tv (
    id_saga                NUMBER(10) NOT NULL,
    titulo                 VARCHAR2(10) NOT NULL,
    anno                   DATE NOT NULL,
    categoria              VARCHAR2(10) NOT NULL,
    genero                 VARCHAR2(10) NOT NULL,
    series_tv_id_serie_tv  NUMBER(10) NOT NULL
);

ALTER TABLE saga_serie_tv ADD CONSTRAINT saga_serie_tv_pk PRIMARY KEY ( id_saga );

CREATE TABLE series_tv (
    id_serie_tv             NUMBER(10) NOT NULL,
    titulo                  VARCHAR2(10) NOT NULL,
    anno                    DATE NOT NULL,
    pais                    VARCHAR2(10) NOT NULL,
    estudio                 VARCHAR2(10) NOT NULL,
    genero                  VARCHAR2(10) NOT NULL,
    clasificacion           VARCHAR2(10) NOT NULL,
    categoria               VARCHAR2(10) NOT NULL,
    duracion                VARCHAR2(10) NOT NULL,
    temporadas              NUMBER(5) NOT NULL,
    directores_id_director  NUMBER(10) NOT NULL,
    reparto_id_reparto      NUMBER(10)
);

ALTER TABLE series_tv ADD CONSTRAINT series_tv_pk PRIMARY KEY ( id_serie_tv );

CREATE TABLE series_tv_favoritas (
    id_favorito            NUMBER(10) NOT NULL,
    usuarios_id_usuario    NUMBER(10) NOT NULL,
    series_tv_id_serie_tv  NUMBER(10) NOT NULL
);

ALTER TABLE series_tv_favoritas ADD CONSTRAINT series_tv_favoritas_pk PRIMARY KEY ( id_favorito );

CREATE TABLE usuarios (
    id_usuario       NUMBER(10) NOT NULL,
    nombre           VARCHAR2(20) NOT NULL,
    direccion        VARCHAR2(15) NOT NULL,
    telefono         NUMBER(10) NOT NULL,
    fecha_nac        DATE NOT NULL,
    genero           VARCHAR2(10) NOT NULL,
    pais             VARCHAR2(10) NOT NULL,
    email            VARCHAR2(15) NOT NULL,
    clave_acceso     NUMBER(5) NOT NULL,
    profesion        VARCHAR2(10) NOT NULL,
    fecha_inclusion  DATE NOT NULL
);

ALTER TABLE usuarios ADD CONSTRAINT usuarios_pk PRIMARY KEY ( id_usuario );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE canciones_favoritas
    ADD CONSTRAINT canciones_favoritas_canciones_fk FOREIGN KEY ( canciones_id_cancion )
        REFERENCES canciones ( id_cancion );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE canciones_favoritas
    ADD CONSTRAINT canciones_favoritas_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

ALTER TABLE canciones
    ADD CONSTRAINT canciones_musico_fk FOREIGN KEY ( musico_id_musico )
        REFERENCES musico ( id_musico );

ALTER TABLE canciones
    ADD CONSTRAINT canciones_productor_fk FOREIGN KEY ( productor_id_productor )
        REFERENCES productor ( id_productor );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE descargas_canciones
    ADD CONSTRAINT descargas_canciones_canciones_fk FOREIGN KEY ( canciones_id_cancion )
        REFERENCES canciones ( id_cancion );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE descargas_canciones
    ADD CONSTRAINT descargas_canciones_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE descargas_pelicula
    ADD CONSTRAINT descargas_pelicula_peliculas_fk FOREIGN KEY ( peliculas_id_pelicula )
        REFERENCES peliculas ( id_pelicula );

ALTER TABLE descargas_pelicula
    ADD CONSTRAINT descargas_pelicula_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE descargas_series_tv
    ADD CONSTRAINT descargas_series_tv_series_tv_fk FOREIGN KEY ( series_tv_id_serie_tv )
        REFERENCES series_tv ( id_serie_tv );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE descargas_series_tv
    ADD CONSTRAINT descargas_series_tv_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

ALTER TABLE formas_pago
    ADD CONSTRAINT formas_pago_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

ALTER TABLE participaciones
    ADD CONSTRAINT participaciones_actores_fk FOREIGN KEY ( actores_id_actor )
        REFERENCES actores ( id_actor );

ALTER TABLE participaciones
    ADD CONSTRAINT participaciones_reparto_fk FOREIGN KEY ( reparto_id_reparto )
        REFERENCES reparto ( id_reparto );

ALTER TABLE peliculas
    ADD CONSTRAINT peliculas_directores_fk FOREIGN KEY ( directores_id_director )
        REFERENCES directores ( id_director );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE peliculas_favoritas
    ADD CONSTRAINT peliculas_favoritas_peliculas_fk FOREIGN KEY ( peliculas_id_pelicula )
        REFERENCES peliculas ( id_pelicula );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE peliculas_favoritas
    ADD CONSTRAINT peliculas_favoritas_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

ALTER TABLE peliculas
    ADD CONSTRAINT peliculas_reparto_fk FOREIGN KEY ( reparto_id_reparto )
        REFERENCES reparto ( id_reparto );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE reproducciones_canciones
    ADD CONSTRAINT reproducciones_canciones_canciones_fk FOREIGN KEY ( canciones_id_cancion )
        REFERENCES canciones ( id_cancion );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE reproducciones_canciones
    ADD CONSTRAINT reproducciones_canciones_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE reproducciones_pelicula
    ADD CONSTRAINT reproducciones_pelicula_peliculas_fk FOREIGN KEY ( peliculas_id_pelicula )
        REFERENCES peliculas ( id_pelicula );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE reproducciones_pelicula
    ADD CONSTRAINT reproducciones_pelicula_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE reproducciones_series_tv
    ADD CONSTRAINT reproducciones_series_tv_series_tv_fk FOREIGN KEY ( series_tv_id_serie_tv )
        REFERENCES series_tv ( id_serie_tv );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE reproducciones_series_tv
    ADD CONSTRAINT reproducciones_series_tv_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

ALTER TABLE saga_pelicula
    ADD CONSTRAINT saga_pelicula_peliculas_fk FOREIGN KEY ( peliculas_id_pelicula )
        REFERENCES peliculas ( id_pelicula );

ALTER TABLE saga_serie_tv
    ADD CONSTRAINT saga_serie_tv_series_tv_fk FOREIGN KEY ( series_tv_id_serie_tv )
        REFERENCES series_tv ( id_serie_tv );

ALTER TABLE series_tv
    ADD CONSTRAINT series_tv_directores_fk FOREIGN KEY ( directores_id_director )
        REFERENCES directores ( id_director );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE series_tv_favoritas
    ADD CONSTRAINT series_tv_favoritas_series_tv_fk FOREIGN KEY ( series_tv_id_serie_tv )
        REFERENCES series_tv ( id_serie_tv );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE series_tv_favoritas
    ADD CONSTRAINT series_tv_favoritas_usuarios_fk FOREIGN KEY ( usuarios_id_usuario )
        REFERENCES usuarios ( id_usuario );

ALTER TABLE series_tv
    ADD CONSTRAINT series_tv_reparto_fk FOREIGN KEY ( reparto_id_reparto )
        REFERENCES reparto ( id_reparto );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            22
-- CREATE INDEX                             0
-- ALTER TABLE                             51
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  17
-- WARNINGS                                 0
