desc ACTORES                                                                                                            
desc CANCIONES                                                                                                          
desc DESCARGASCANCIONES                                                                                                 
desc DESCARGASPELICULA                                                                                                  
desc DESCARGASSERIES                                                                                                    
desc DIRECTORES                                                                                                         
desc FORMASPAGO                                                                                                         
desc MUSICOS                                                                                                            
desc PARTICIPANTES                                                                                                      
desc PELICULAS                                                                                                          
desc PREFERENCIASCANCIONES                                                                                              
desc PREFERENCIASPELICULA                                                                                               
desc PREFERENCIASSERIE                                                                                                  
desc PRODUCTORES                                                                                                        
desc REPARTOS                                                                                                           
desc REPRODUCCIONESPELICULA                                                                                             
desc REPRODUCCIONESSERIES                                                                                               
desc REPRODUCIONESCANCIONES                                                                                             
desc SAGASERIE                                                                                                          
desc SAGASPELICULA                                                                                                      
desc SERIES                                                                                                             
desc USUARIOS                                                                                                           
/